# ROFL Compose definition for the RedPill proxy service.
# IMPORTANT: The `image` must be a public OCI image (e.g., ghcr.io or docker.io)
# so ROFL nodes can pull it. Replace the placeholder below with your image.
# You can build and push with:
#   docker buildx build --platform linux/amd64 -t ghcr.io/<owner>/<repo>/redpill-proxy:latest packages/nextjs/redpill
#   docker push ghcr.io/<owner>/<repo>/redpill-proxy:latest

services:
  redpill-proxy:
    image: ghcr.io/REPLACE_ME_OWNER/REPLACE_ME_REPO/redpill-proxy:latest
    platform: linux/amd64
    # If you prefer immutable references, pin to a digest:
    # image: ghcr.io/<owner>/<repo>/redpill-proxy:latest@sha256:<digest>

    # The server listens on PORT (defaults to 5000). You can override the host port below.
    ports:
      - "8080:5000"

    environment:
      # ROFL secrets are exposed as env vars; define secret named REDPILL
      # with `oasis rofl secret set REDPILL -` and it will inject here.
      - REDPILL=${REDPILL}
      # Optional: explicit PORT; the app defaults to 5000 otherwise.
      - PORT=5000

    # If you plan to use rofl-appd REST API from your container, also mount the socket:
    # volumes:
    #   - /run/rofl-appd.sock:/run/rofl-appd.sock
